project:
  type: website
  output-dir: docs

website:
  title: "Peter D Smits"
  site-url: https://psmits.github.io/
  description: "This is Peter Smits' personal site."
  navbar:
    right:
      - text: Home
        href: index.qmd
      - icon: github
        href: https://github.com/psmits
format:
  html:
    theme: yeti
    css: styles.css



